version: '3.8'
services:
  coolleaf-app:
    build: .  # This will look for the Dockerfile in the current directory
    container_name: coolleaf-app
    ports:
      - "9080:8080"
    restart: always
    # If you haven't created the logs directory on the server,
    # it's recommended to comment this out or make sure the directory exists
    # volumes:
    #   - ./logs:/app/logs