spring:
  application:
    name: CoolLeaf
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: api/rest
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 2592000
          cache-public: true

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: "at-least-32-character-long-secret-key-for-security"
  expiration: 2592000000 # 30 days in ms

r2:
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  endpoint: ${R2_ENDPOINT}
  bucket-name: coollib-review

management:
  endpoints:
    web:
      exposure:
        include: "health"